name: Build docker image for server and web

on:
  push:
    branches:    
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build docker image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: sudo docker-compose build
      - name: run services
        run: |
          sudo docker-compose down
          sudo docker-compose up -d
      - name: reduce disk volume usage
        run: |
          sudo docker images | grep none | awk '{print $3}' | xargs sudo docker rmi || true
