name: Build docker image for server and web

on:
  push:
    branches:    
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build docker image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: replace env
        run: |
          sed -i 's/SECRET_KEY=/SECRET_KEY=${{ secrets.SECRET_KEY }}/g' .env
          sed -i 's/JWT_SECRET_KEY=/JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}/g' .env
          sed -i 's/mongo-password/${{ secrets.MONGO_PASSWORD }}/g' init-mongo.js
          sed -i 's/"private_key":\ ""/"private_key":\ "${{ secrets.PRIVATE_KEY }}"/g' server/google-tts-key.json
          sed -i 's/"private_key_id":\ ""/"private_key_id":\ "${{ secrets.PRIVATE_KEY_ID }}"/g' server/google-tts-key.json
      - name: build
        run: sudo docker-compose build
      - name: run services
        run: |
          sudo docker-compose down
          sudo docker-compose up -d
      - name: reduce disk volume usage
        run: |
          sudo docker images | grep none | awk '{print $3}' | xargs sudo docker rmi || true
